import { useEffect, useRef, useState } from "react"
import {
  DEMO_COPILOT_ANSWERS,
  DEMO_COPILOT_FALLBACK,
  DEMO_COPILOT_SUGGESTIONS,
} from "../api/demo"
import type { CopilotResponse } from "../api/types"
import { usePreview } from "../hooks/useResource"
import {
  Button,
  IllustrativeTag,
  PageHeader,
  Panel,
  SectionHeader,
} from "../components/ui"
import { DEMO_CAMPAIGN } from "../api/demo"

type Turn = { q: string; a: CopilotResponse | null; failed?: boolean }

export default function CampaignCopilot() {
  const { state } = usePreview()
  const unavailable = state === "error"
  const [turns, setTurns] = useState<Turn[]>([])
  const [input, setInput] = useState("")
  const busy = turns.some((t) => !t.a && !t.failed)
  const end = useRef<HTMLDivElement>(null)

  useEffect(() => {
    end.current?.scrollIntoView({ block: "nearest", behavior: "smooth" })
  }, [turns])

  const ask = (q: string) => {
    if (!q.trim() || busy) return
    setInput("")
    setTurns((t) => [...t, { q, a: null }])
    // TODO(integration): send { campaign_id, question } to the backend Copilot. Never call an LLM from the browser.
    setTimeout(() => {
      setTurns((t) =>
        t.map((x, i) =>
          i === t.length - 1
            ? { ...x, a: DEMO_COPILOT_ANSWERS[q] ?? DEMO_COPILOT_FALLBACK }
            : x,
        ),
      )
    }, 900)
  }

  return (
    <div className="space-y-6">
      <PageHeader
        step="09"
        title="Campaign Copilot"
        lede="Ask questions about this campaign. Answers are generated by the backend from campaign, scoring, optimization and experiment outputs — and list the fields they used."
        actions={<IllustrativeTag show={turns.length > 0} />}
      />

      <div className="grid gap-6 lg:grid-cols-[1fr_280px]">
        <Panel className="flex min-h-[520px] flex-col">
          <div className="flex items-center justify-between border-b border-line px-5 py-3 text-[12px]">
            <span className="text-mute">
              Grounded in{" "}
              <span className="font-mono text-ink">
                {DEMO_CAMPAIGN.campaign_id}
              </span>{" "}
              · {DEMO_CAMPAIGN.name}
            </span>
            <span
              className={`flex items-center gap-1.5 ${
                unavailable ? "text-neg" : "text-mute"
              }`}
            >
              <span
                className={`size-1.5 rounded-full ${
                  unavailable ? "bg-neg" : "bg-pos"
                }`}
              />
              {unavailable ? "Unavailable" : "Ready"}
            </span>
          </div>

          <div
            className="scroll-quiet flex-1 space-y-6 overflow-y-auto p-5"
            aria-live="polite"
          >
            {unavailable ? (
              <div className="border-l-2 border-neg py-1 pl-4">
                <p className="text-[13.5px] font-semibold text-neg">
                  Copilot unavailable
                </p>
                <p className="mt-1 max-w-lg text-[13px] text-ink-2">
                  The Copilot service is not responding. The rest of
                  CampaignLift is unaffected — audience, uplift, budget and
                  experiment views use separate data.
                </p>
              </div>
            ) : turns.length === 0 ? (
              <div className="max-w-lg">
                <p className="text-[14px] font-medium">
                  Start with a question about this campaign.
                </p>
                <p className="mt-1 text-[13px] text-mute">
                  The Copilot only answers from model and campaign outputs. If
                  the context doesn't contain an answer, it will say so.
                </p>
              </div>
            ) : (
              turns.map((t, i) => (
                <article key={i} className="space-y-3">
                  <p className="ml-auto w-fit max-w-[85%] rounded-[4px] bg-ink px-3 py-2 text-[13px] text-white">
                    {t.q}
                  </p>
                  {t.a ? (
                    <div className="max-w-[92%] border-l-2 border-primary pl-4">
                      <p className="text-[13.5px] leading-relaxed text-ink">
                        {t.a.answer}
                      </p>
                      <div className="mt-3">
                        <p className="font-mono text-[10.5px] tracking-wider text-mute uppercase">
                          Context fields used
                        </p>
                        <ul className="mt-1.5 flex flex-wrap gap-1.5">
                          {t.a.context_fields_used.map((f) => (
                            <li
                              key={f}
                              className="rounded-[3px] bg-sunken px-1.5 py-0.5 font-mono text-[11px] text-ink-2"
                            >
                              {f}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  ) : (
                    <p className="animate-pulse-soft pl-4 text-[12.5px] text-mute">
                      Reading campaign context…
                    </p>
                  )}
                </article>
              ))
            )}
            <div ref={end} />
          </div>

          <form
            className="flex gap-2 border-t border-line p-3"
            onSubmit={(e) => {
              e.preventDefault()
              ask(input)
            }}
          >
            <label htmlFor="q" className="sr-only">
              Ask a question
            </label>
            <input
              id="q"
              value={input}
              disabled={unavailable}
              onChange={(e) => setInput(e.target.value)}
              placeholder={
                unavailable
                  ? "Copilot unavailable"
                  : "Ask about customers, segments, strategy or budget…"
              }
              className="h-9 flex-1 rounded-[4px] border border-line-strong bg-surface px-3 text-[13.5px] disabled:bg-sunken"
            />
            <Button
              type="submit"
              variant="primary"
              className="h-9"
              disabled={unavailable || busy || !input.trim()}
            >
              Ask
            </Button>
          </form>
        </Panel>

        <aside className="space-y-6">
          <Panel className="p-4">
            <SectionHeader title="Suggested questions" />
            <ul className="space-y-1">
              {DEMO_COPILOT_SUGGESTIONS.map((s) => (
                <li key={s}>
                  <button
                    disabled={unavailable || busy}
                    onClick={() => ask(s)}
                    className="w-full rounded-[3px] px-2 py-1.5 text-left text-[12.5px] text-ink-2 hover:bg-paper hover:text-ink disabled:opacity-40"
                  >
                    {s}
                  </button>
                </li>
              ))}
            </ul>
          </Panel>
          <div className="px-1 text-[12px] leading-relaxed text-mute">
            The Copilot is served by the backend. No model keys are held in the
            browser. Answers can be wrong — verify against the underlying
            screens.
          </div>
        </aside>
      </div>
    </div>
  )
}
